maps/op4_meanie.res
sound/misc/awcrp2.wav
sound/misc/baby.wav
sound/misc/bastards.wav
sound/misc/bleeeat.wav
sound/misc/borg.wav
sound/misc/brawwrr.wav
sound/misc/chick.wav
sound/misc/cometo.wav
sound/misc/cry.wav
sound/misc/cryloud.wav
sound/misc/damn.wav
sound/misc/damnit3.wav
sound/misc/damnsob.wav
sound/misc/dog2.wav
sound/misc/dog3.wav
sound/misc/dog4.wav
sound/misc/dog5.wav
sound/misc/doh9.wav
sound/misc/dohhh.wav
sound/misc/fart.wav
sound/misc/good.wav
sound/misc/ha-ha.wav
sound/misc/hello.wav
sound/misc/hi2.wav
sound/misc/kick.wav
sound/misc/lmao.wav
sound/misc/lol.wav
sound/misc/lol2.wav
sound/misc/lucky.wav
sound/misc/myass.wav
sound/misc/nacho.wav
sound/misc/olddude.wav
sound/misc/ooorgle.wav
sound/misc/outta.wav
sound/misc/ow.wav
sound/misc/scream.wav
sound/misc/seethat.wav
sound/misc/shut-up.wav
sound/misc/sob.wav
sound/misc/sob3.wav
sound/misc/threaten.wav
sound/misc/win.wav
sound/misc/woo-hoo.wav
sound/misc/wtf.wav
sound/misc/yo.wav