maps/hl_iceworld.txt
maps/hl_iceworld.res
gfx/env/snowup.tga
gfx/env/snowdn.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowft.tga
gfx/env/snowbk.tga
sound/buttons/spark1.wav
sound/buttons/spark2.wav
sound/buttons/spark3.wav
sound/buttons/spark4.wav
sound/erdos/balls.wav
sound/erdos/bruh.wav
sound/erdos/bye.wav
sound/erdos/fatal.wav
sound/erdos/gg.wav
sound/erdos/haha.wav
sound/erdos/hello.wav
sound/erdos/lego.wav
sound/erdos/ns.wav
sound/erdos/oh.wav
sound/erdos/oki.wav
sound/erdos/omg.wav
sound/erdos/ooo.wav
sound/erdos/runnin.wav
sound/erdos/shit.wav
sound/erdos/uhh.wav
sound/erdos/wtf.wav
sound/erdos/XD.wav
sound/erdos/yaay.wav
sound/erdos/yeah.wav